// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGL-PDJDYICBwQnO7Bh6tO9mMsHSCpuO4',
    appId: '1:714352450375:web:2b5aa26b424885c7bf4a62',
    messagingSenderId: '714352450375',
    projectId: 'gestion-y-control-agro',
    authDomain: 'gestion-y-control-agro.firebaseapp.com',
    storageBucket: 'gestion-y-control-agro.firebasestorage.app',
    measurementId: 'G-TGJP3J1CZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlCBrhGdCq-EeuM3Qo6J3FYYDRD3urKw',
    appId: '1:714352450375:android:76840e211b88a566bf4a62',
    messagingSenderId: '714352450375',
    projectId: 'gestion-y-control-agro',
    storageBucket: 'gestion-y-control-agro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBewiUa16VAnxE5l_t1tlnqPB3caSe3BLw',
    appId: '1:714352450375:ios:ff0f8215a524424fbf4a62',
    messagingSenderId: '714352450375',
    projectId: 'gestion-y-control-agro',
    storageBucket: 'gestion-y-control-agro.firebasestorage.app',
    iosClientId:
        '714352450375-r68l4hrd58nfbovt88nc6s4ioc49nu2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlgestionagro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBewiUa16VAnxE5l_t1tlnqPB3caSe3BLw',
    appId: '1:714352450375:ios:ff0f8215a524424fbf4a62',
    messagingSenderId: '714352450375',
    projectId: 'gestion-y-control-agro',
    storageBucket: 'gestion-y-control-agro.firebasestorage.app',
    iosClientId:
        '714352450375-r68l4hrd58nfbovt88nc6s4ioc49nu2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlgestionagro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGL-PDJDYICBwQnO7Bh6tO9mMsHSCpuO4',
    appId: '1:714352450375:web:b6930fff610a748bbf4a62',
    messagingSenderId: '714352450375',
    projectId: 'gestion-y-control-agro',
    authDomain: 'gestion-y-control-agro.firebaseapp.com',
    storageBucket: 'gestion-y-control-agro.firebasestorage.app',
    measurementId: 'G-THPPNFCRH5',
  );
}
